# Generated by binpac_quickstart

refine flow opcua_Flow += {
	function proc_opcua_message(msg: opcua_PDU): bool
		%{
		zeek::BifEvent::enqueue_opcua_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

refine typeattr opcua_PDU += &let {
	proc: bool = $context.flow.proc_opcua_message(this);
};
