// Generated by binpac_quickstart

#include "Plugin.h"
#include "analyzer/Component.h"

#include "opcua.h"

namespace plugin { namespace Demo_opcua { Plugin plugin; } }

using namespace plugin::Demo_opcua;
using namespace zeek;

zeek::plugin::Configuration Plugin::Configure()
	{
	AddComponent(new ::analyzer::Component("opcua",
	             ::analyzer::Demo_opcua::opcua_Analyzer::InstantiateAnalyzer));

	zeek::plugin::Configuration config;

	config.name = "Demo::opcua";
	config.description = "opcua Protocol Analyzer";

	config.version.major = 0;
	config.version.minor = 1;
	config.version.patch = 0;

	return config;
	}

